name: 'Run tests whenever a pull request is opened'

on: [pull_request]

jobs:
    test:
        uses: network-rail-business-systems/workflows/.github/workflows/unit-tests.yml@main
        with:
            artisan: false
            env: false
            npm: false
            php: '8.3'
